# https://docs.microsoft.com/azure/devops/pipelines/yaml-schema

variables:
  - group: 'Secrets'

stages:
- stage: BuildStage
  displayName: 'Build'
  jobs:
  - job: BuildJob
    displayName: 'Build'
    pool:
      vmImage: 'ubuntu-latest'
    workspace:
      clean: all

    steps:
    - checkout: self
      fetchDepth: 0

    - task: UseDotNet@2
      displayName: 'Install .NET SDK'
      inputs:
        useGlobalJson: true

    - task: DotNetCoreCLI@2
      displayName: 'dotnet format'
      inputs:
        command: 'custom'
        custom: 'format'
        arguments: '--verify-no-changes'

    - task: DotNetCoreCLI@2
      displayName: 'Build solution'
      inputs:
        command: 'build'
        projects: |
          Swashbuckle.sln

    - task: DotNetCoreCLI@2
      displayName: 'Pack'
      inputs:
        command: pack
        packDirectory: 'artifacts'

    - publish: '$(Build.Repository.LocalPath)/artifacts'
      displayName: 'Publish artifacts'
      artifact: 'packages'

    - task: DotNetCoreCLI@2
      displayName: 'Push to GitHub'
      condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
      inputs:
        command: 'custom'
        custom: 'nuget'
        arguments: 'push artifacts/*.nupkg --api-key $(GitHubPackageRepositoryKey) --source https://nuget.pkg.github.com/ctyar/index.json'